apply/urls.py
from django.urls import path
from rest_framework import routers
from  . import views


urlpatterns = [
    path('', views.ShiftTopView.as_view(), name='shift_top'),
    path('submit/', views.SubmitView.as_view(), name='submit'),
    path('confirm/', views.ConfirmView.as_view(), name='confirm'),
]

app_name = 'apply'

router = routers.DefaultRouter()
router.register('shift', views.ShiftViewSet)

shift/urls.py
from django.contrib import admin
from django.urls import path, include
from apply.urls import router
from users.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('shop/', include('shop.urls')),
    path('shift/', include('apply.urls')),
    path('api/', include(router.urls)),
]

shop/urls.py
from django.urls import path
from  . import views


urlpatterns = [
    path('', views.ShopTopView.as_view(), name='top'),
    path('create/', views.ShopCreateView.as_view(), name='create'),
    path('join/', views.ShopJoinView.as_view(), name='join'),
]

users/urls.py
from django.urls import path
from  . import views


urlpatterns = [
    path('', views.UserTopView.as_view(), name='account_top'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
import  uuid
from shop.models import Shop


class UserManager(BaseUserManager):
    def create_user(self, email, name, password=None, **extra_fields):
        user = self.model(
            email=self.normalize_email(email),
            name=name,
            **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        print('saved')

        return user

    def create_superuser(self, email, name, password, **extra_fields):
        user = self.create_user(email, name, password)
        user.is_admin = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser):
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        db_table = 'users_user'

    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, unique=True, editable=False, )
    name = models.CharField(verbose_name='name', max_length=200, )
    email = models.EmailField(verbose_name='email', max_length=200, unique=True, )
    is_staff = models.BooleanField(default=False, )
    is_active = models.BooleanField(default=True, )
    is_owner = models.BooleanField(default=False, )
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, blank=True, null=True, )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', ]

    def __str__(self):
        return self.name
    
    def get_username(self):
        return self.name

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from . import models

class CreateUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control form-control-lg'
        self.fields['name'].widget.attrs['class'] = 'form-control form-control-lg'
        self.fields['password1'].widget.attrs['class'] = 'form-control form-control-lg'
        self.fields['password2'].widget.attrs['class'] = 'form-control form-control-lg'

    email = forms.EmailField(
        label='EMAIL',
        max_length=200,
    )
    name = forms.CharField(
        label='NAME',
        max_length=200,
    )
    password1 = forms.CharField(
        label='PASSWORD',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='PASSORD CONFIRMATION',
        widget=forms.PasswordInput
    )

    class Meta:
        model = models.User
        fields = ('email', 'name', )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('name')
        password = self.cleaned_data.get('password1')
        user = models.User(name=username, email=email)
        user.set_password(password)
        user.save()

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models


class SignupView(generic.CreateView):
    template_name = 'users/signup.html'
    form_class = forms.CreateUserForm
    model = models.User

    def get_context_data(self):
        context = super().get_context_data()
        context['auth'] = self.request.user.is_authenticated

        return context

    def get_success_url(self):
        return reverse_lazy('login')
    
    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect('/accounts/login')


class UserTopView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'users/top.html'

    def get_context_data(self):
        context = super().get_context_data()
        user = self.request.user
        context['user'] = user
        context['auth'] = self.request.user.is_authenticated

        return context


class HomeView(generic.TemplateView):
    template_name = 'users/home.html'

    def get_context_data(self):
        context = super().get_context_data()
        context['auth'] = self.request.user.is_authenticated
        
        return context

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'users/css/user.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block css %}{% endblock %}
    {% block js %}{% endblock %}
  </head>
  <body>
    <header>
      <div class="h-right">
        <p>{% block h1 %}{% endblock %}</p>
      </div>
      {% if auth %}
        <div class="h-left">
          <nav>
            <ul>
              <li>
                <a href="{% url 'account_top' %}">ACCOUNT TOP</a>
              </li>
              {% if user.shop is None %}
                <li>
                  <a href="{% url 'create' %}">CREATE SHOP</a>
                </li>
                <li>
                  <a href="{% url 'join' %}">JOIN SHOP</a>
                </li>
              {% else %}
              <li>
                <a href="{% url 'top' %}">SHOP TOP</a>
              </li>
                <li>
                  <a href="{% url 'apply:shift_top' %}">SHIFT TOP</a>
                </li>
                <li>
                  <a href="{% url 'apply:submit' %}">SUBMISSION</a>
                </li>
                {% if user.is_owner %}
                <li>
                  <a href="{% url 'apply:confirm' %}">CONFIRMATION</a>
                </li>
                {% endif %}
              {% endif %}
            </ul>
          </nav>
        </div>
      {% endif %}
    </header>
    <div class="wrap">
      {% block content %}{% endblock %}
    </div>
    {% block extra %}{% endblock %}
  </body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}HOME{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'users/css/user_home.css' %}">
{% endblock %}

{% block js %}
{% endblock %}

{% block h1 %}
<h1>HOME</h1>
{% endblock %}

{% block content %}
{% if auth %}
<h2>WELCOME BACK, {{ user.name }}.</h2>
{% else %}
<h2>Thank you for seeing our site.</h2>
<p>Please click <a href="{% url 'signup' %}">HERE</a> to create new account.</p>
<p>If you already have account, <a href="{% url 'login' %}">LOG IN</a> here</p>
{% endif %}
{% endblock %}

users/templates/users/signup.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}SIGN UP{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'users/css/user_signup.css' %}">
{% endblock %}

{% block js %}
{% endblock %}

{% block h1 %}
<h1>SIGN UP</h1>
{% endblock %}

{% block content %}
<div class="signup">
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">SIGN UP</button>
  </form>
  <p>or</p>
  <a href="{% url 'password_reset' %}">Forgot Password</a>
</div>
{% endblock %}

users/templates/users/top.html
{% extends 'users/base.html' %}
{% load static %}

{% block title%}MY PAGE{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'users/css/user_top.css' %}">
{% endblock %}

{% block js %}
{% endblock %}

{% block h1 %}
<h1>MY PAGE</h1>
{% endblock %}

{% block content %}
<div class="user-body">
  <table class="table">
    <thead>
      <tr>
        <th>USER NAME</th>
        <th>EMAIL</th>
        <th>BELONG TO</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ user.name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.shop }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}